# Generated by Django 6.0.5 on 2026-05-20 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('role', models.CharField(choices=[('COORDINATOR', 'Coordonnateur'), ('VICE_COORDINATOR', 'Vice-Coordonnateur'), ('ISO_EXPERT', 'Expert Veille ISO'), ('LEGAL', 'Légiste'), ('ENVIRONMENTAL', 'Environnementaliste'), ('PLANNER', 'Planificateur'), ('ECONOMIST', 'Économiste'), ('SCIENTIFIC', 'Conseiller Scientifique'), ('ACCOUNTANT', 'Comptable'), ('ENQUIRY_MANAGER', 'Responsable Enquêtes'), ('INDUSTRIAL', 'Liaison Industrielle'), ('COMMUNICATOR', 'Communicateur'), ('EXECUTIVE', 'Assistant Exécutif'), ('CARTOGRAPHER', 'Cartographe SIG'), ('DATA_ENTRY', 'Opérateur de Saisie'), ('IT_ADMIN', 'Administrateur IT')], default='COORDINATOR', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership CTC',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('position', models.CharField(choices=[('MINISTER', 'Ministre des ITP'), ('SG_ITP', 'Secrétaire Général aux ITP'), ('CABINET', 'Directeur de Cabinet')], max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_position', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Niveau Exécutif',
                'verbose_name_plural': 'Niveaux Exécutifs',
            },
        ),
        migrations.CreateModel(
            name='OriginStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('expected_expert_count', models.PositiveIntegerField(default=0, help_text="Nombre attendu d'experts")),
                ('giron', models.CharField(choices=[('ADMIN', 'Administration publique'), ('OFFICES', 'Établissements publics & Offices'), ('ORDERS', 'Ordres professionnels'), ('ACADEMIA', 'Académiques & Recherche'), ('METROLOGY', 'Métrologie & Société civile'), ('PRIVATE', 'Secteur privé')], max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Structure d'Origine",
                'verbose_name_plural': "Structures d'Origine",
                'ordering': ['giron', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(default='Cellule Technique de Coordination', max_length=200)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctc_coordinator', to='experts.expert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='ctc_member_of', through='governance.CTCMembership', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vice_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctc_vice_coordinator', to='experts.expert')),
            ],
            options={
                'verbose_name': 'Cellule Technique',
                'verbose_name_plural': 'Cellules Techniques',
            },
        ),
        migrations.AddField(
            model_name='ctcmembership',
            name='ctc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance.technicalcell'),
        ),
        migrations.AlterUniqueTogether(
            name='ctcmembership',
            unique_together={('ctc', 'expert')},
        ),
    ]
