# Generated by Django 6.0.5 on 2026-06-01 08:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expert_ctm_choices_expert_ctm'),
        ('governance', '0002_add_hierarchy_models'),
        ('norms', '0003_norme_lock_timeout_norme_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotagemembreship',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président (Bureau)'), ('VICE_PRESIDENT', 'Vice-Président (Bureau)'), ('SECRETARY', 'Secrétaire (Bureau)'), ('RAPPORTEUR', 'Rapporteur Général (Bureau)'), ('CONSEILLER_POLITIQUE', 'Conseiller Institutionnel et Politique'), ('ADMIN_TECH_FIN', 'Administrateur Technique et Financier'), ('PARTENAIRE_SOC_CIV', 'Partenaire Sectoriel et Société Civile'), ('CONSEILLER', 'Conseiller')], default='CONSEILLER', max_length=50),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Complétée'), ('BLOCKED', 'Bloquée'), ('ON_HOLD', 'En attente')], default='PLANNED', max_length=50)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='experts.expert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('norme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('working_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='governance.wg')),
            ],
            options={
                'verbose_name': 'Tâche WG',
                'verbose_name_plural': 'Tâches WG',
                'ordering': ['-created_at'],
            },
        ),
    ]
