# Generated by Django 6.0.5 on 2026-06-08 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expert_accepted_at_expert_accepted_by_and_more'),
        ('governance', '0003_alter_pilotagemembreship_role_tache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteNominatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('role', models.CharField(choices=[('PRESIDENT', 'Président (Bureau)'), ('VICE_PRESIDENT', 'Vice-Président (Bureau)'), ('SECRETARY', 'Secrétaire (Bureau)'), ('RAPPORTEUR', 'Rapporteur Général (Bureau)'), ('CONSEILLER_POLITIQUE', 'Conseiller Institutionnel et Politique'), ('ADMIN_TECH_FIN', 'Administrateur Technique et Financier'), ('PARTENAIRE_SOC_CIV', 'Partenaire Sectoriel et Société Civile')], max_length=50)),
                ('title', models.CharField(help_text='Intitulé nominatif exact du poste, tel que rédigé dans le manuel organisationnel', max_length=300)),
                ('quota_line', models.PositiveSmallIntegerField(blank=True, help_text='Référence « Ligne X » du Tableau 1 du manuel organisationnel', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_nominatifs', to='governance.comitepilotage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(blank=True, help_text='Expert nommé à ce poste — laisser vide tant que le poste est vacant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_nominatifs_occupes', to='experts.expert')),
                ('required_structure', models.ForeignKey(blank=True, help_text="Structure d'origine exigée pour ce poste (ex: Cabinet du Ministre = Quota Ligne 2)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_nominatifs', to='experts.structure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poste Nominatif (Pilotage)',
                'verbose_name_plural': 'Postes Nominatifs (Pilotage)',
                'ordering': ['comite', 'order'],
                'unique_together': {('comite', 'title')},
            },
        ),
    ]
