# Generated by Django 6.0.5 on 2026-06-08 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expert_accepted_at_expert_accepted_by_and_more'),
        ('governance', '0006_add_permission_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCOperationalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('restricted_resource', models.CharField(help_text="Module ou ressource CTC dont l'accès temporaire est demandé", max_length=300)),
                ('reason', models.TextField(verbose_name="Demande d'ouverture de droits temporaires ou de transmission urgente de données")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctc_requests', to='experts.expert', verbose_name='Demandeur')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctc_reviews', to='experts.expert', verbose_name='Examiné par (Assistant Exécutif)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Opérationnelle CTC',
                'verbose_name_plural': 'Demandes Opérationnelles CTC',
                'ordering': ['-created_at'],
            },
        ),
    ]
