# Generated by Django 6.0.5 on 2026-06-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expert_accepted_at_expert_accepted_by_and_more'),
        ('governance', '0007_add_ctc_operational_request'),
        ('norms', '0004_normevote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCProcessus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('current_stage', models.CharField(choices=[('RECEPTION', 'Étape 1 — Réception, Numérisation & Cadrage'), ('GEOSPATIAL', 'Étape 2 — Traitement Géospatial SIG (si applicable)'), ('MULTI_REVIEW', 'Étape 3 — Toilettage Multi-Critères (examens parallèles)'), ('INDUSTRIAL', 'Étape 4 — Consultation Industrielle FEC'), ('SIGNED_OUT', 'Étape 5 — Signé & Transmis au Comité de Pilotage')], default='RECEPTION', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, help_text='Date de fin de mise en page et indexation par les Opérateurs de Saisie', null=True)),
                ('intake_validated_at', models.DateTimeField(blank=True, null=True)),
                ('requires_sig', models.BooleanField(default=False, help_text="Cocher si la norme traite d'infrastructures linéaires nécessitant géolocalisation")),
                ('sig_completed_at', models.DateTimeField(blank=True, null=True)),
                ('it_stored_at', models.DateTimeField(blank=True, help_text='Date de dépôt en base sécurisée par les Techniciens IT', null=True)),
                ('multi_review_started_at', models.DateTimeField(blank=True, null=True)),
                ('all_reviews_completed', models.BooleanField(default=False)),
                ('all_reviews_completed_at', models.DateTimeField(blank=True, null=True)),
                ('industrial_completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('transmitted_to_pilotage_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('intake_validated_by', models.ForeignKey(blank=True, help_text="Coordonnateur qui a validé l'introduction dans le circuit", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_validated_norms', to='experts.expert')),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ctc_processus', to='norms.norme')),
                ('received_by', models.ForeignKey(blank=True, help_text='Assistant Exécutif qui a enregistré le dossier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_norms', to='experts.expert')),
                ('sig_completed_by', models.ForeignKey(blank=True, help_text='Ingénieur Cartographe SIG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sig_completed_norms', to='experts.expert')),
                ('signed_out_by', models.ForeignKey(blank=True, help_text='Coordonnateur Technique Principal qui certifie la fin du toilettage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_out_norms', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processus CTC',
                'verbose_name_plural': 'Processus CTC',
                'ordering': ['-created_at'],
            },
        ),
    ]
