# Generated by Django 6.0.5 on 2026-06-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expert_accepted_at_expert_accepted_by_and_more'),
        ('governance', '0008_ctcprocessus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctcprocessus',
            name='received_by_president',
            field=models.ForeignKey(blank=True, help_text='Président du Comité de Pilotage Élargi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_received_norms', to='experts.expert'),
        ),
        migrations.AddField(
            model_name='ctcprocessus',
            name='received_by_president_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctcprocessus',
            name='received_by_rapporteur',
            field=models.ForeignKey(blank=True, help_text='Rapporteur Général du Comité de Pilotage Élargi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporteur_received_norms', to='experts.expert'),
        ),
        migrations.AddField(
            model_name='ctcprocessus',
            name='received_by_rapporteur_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
