# Generated by Django 6.0.5 on 2026-06-10 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expert_accepted_at_expert_accepted_by_and_more'),
        ('governance', '0009_ctcprocessus_received_by_president_and_more'),
        ('norms', '0005_norme_norm_type_norme_target_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormeCadrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('current_stage', models.CharField(choices=[('PROPOSED', 'Phase 1.1 — Orientation stratégique (Président)'), ('EXPERTS_REVIEW', 'Phase 1.2 — Validation des experts WG (1er & 2nd Vice-Présidents)'), ('MANDATE_FORMALIZATION', 'Phase 1.3 — Mandat opérationnel formalisé (Secrétaire)'), ('SCHEDULED', 'Phase 1.4 — Chronogramme & ordre de service (Rapporteur Général)'), ('PV_VERIFICATION', "Phase 2.1 — Vérification du PV de l'Assemblée Plénière (Secrétaire)"), ('CONFORMITY_QUITUS', 'Phase 2.2 — Quitus de conformité technique (1er & 2nd Vice-Présidents)'), ('FINAL_VALIDATION', 'Phase 2.3 — Validation finale & signature (Président)'), ('COMPLETED', "Terminé — Transmis au Ministre (Arrêté d'Homologation)")], default='PROPOSED', max_length=24)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('strategic_orientation', models.TextField(blank=True, help_text='Orientations stratégiques formulées pour la mise en chantier de cette norme')),
                ('onic_validated_at', models.DateTimeField(blank=True, null=True)),
                ('onic_notes', models.TextField(blank=True, help_text='Avis sur la légitimité technique des experts WG du giron Ingénierie')),
                ('btp_validated_at', models.DateTimeField(blank=True, null=True)),
                ('btp_notes', models.TextField(blank=True, help_text='Avis sur le mandat opérationnel des experts WG du secteur BTP')),
                ('mandate_formalized_at', models.DateTimeField(blank=True, null=True)),
                ('operational_mandate', models.TextField(blank=True, help_text='Mandat opérationnel initial et méthodologie scientifique transmis aux CTM')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_ctm_review', models.DateField(blank=True, help_text='Date butoir — Remise des travaux du CTM/WG', null=True)),
                ('deadline_ctc_handoff', models.DateField(blank=True, help_text='Date butoir — Transmission du dossier à la CTC', null=True)),
                ('deadline_pilotage_review', models.DateField(blank=True, help_text='Date butoir — Retour devant le Comité de Pilotage', null=True)),
                ('transmitted_to_ctc_at', models.DateTimeField(blank=True, help_text="Date de transmission de l'ordre de service à la CTC", null=True)),
                ('pv_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pv_reference', models.CharField(blank=True, help_text="Référence du PV de l'Assemblée Plénière", max_length=100)),
                ('onic_quitus_at', models.DateTimeField(blank=True, null=True)),
                ('btp_quitus_at', models.DateTimeField(blank=True, null=True)),
                ('final_validated_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reference', models.CharField(blank=True, help_text='Référence de la résolution signée par le Président', max_length=100)),
                ('transmitted_to_ministry_at', models.DateTimeField(blank=True, help_text="Date de transmission au Ministre pour l'Arrêté d'Homologation", null=True)),
                ('btp_quitus_by', models.ForeignKey(blank=True, help_text='2nd Vice-Président — AIBTP/CNIRS-BTP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_quitus_btp', to='experts.expert')),
                ('btp_validated_by', models.ForeignKey(blank=True, help_text='2nd Vice-Président — AIBTP/CNIRS-BTP (giron Construction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_valides_btp', to='experts.expert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('final_validated_by', models.ForeignKey(blank=True, help_text='Président du Comité de Pilotage Élargi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_valides_finaux', to='experts.expert')),
                ('mandate_formalized_by', models.ForeignKey(blank=True, help_text='Secrétaire du Comité de Pilotage Élargi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_mandats_formalises', to='experts.expert')),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadrage', to='norms.norme')),
                ('onic_quitus_by', models.ForeignKey(blank=True, help_text='1er Vice-Président — ONIC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_quitus_onic', to='experts.expert')),
                ('onic_validated_by', models.ForeignKey(blank=True, help_text='1er Vice-Président — ONIC (giron Ingénierie)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_valides_onic', to='experts.expert')),
                ('opened_by', models.ForeignKey(blank=True, help_text='Président du Comité de Pilotage Élargi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_ouverts', to='experts.expert')),
                ('pv_verified_by', models.ForeignKey(blank=True, help_text='Secrétaire du Comité de Pilotage Élargi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_pv_verifies', to='experts.expert')),
                ('scheduled_by', models.ForeignKey(blank=True, help_text='Rapporteur Général — SG-ITP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadrages_planifies', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadrage Bureau Directoire',
                'verbose_name_plural': 'Cadrages Bureau Directoire',
                'ordering': ['-created_at'],
            },
        ),
    ]
