# Generated by Django 6.0.5 on 2026-06-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Envoyé'), ('delivered', 'Distribué'), ('read', 'Lu')], default='sent', max_length=12),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
