# Generated by Django 6.0.5 on 2026-06-15 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('scope', models.CharField(choices=[('expert', 'Expert'), ('ctc', 'Cellule Technique de Coordination'), ('pilotage', 'Comité de Pilotage')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Agent IA',
                'verbose_name_plural': 'Sessions Agent IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('tool', 'Outil')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia_agent.agentsession')),
            ],
            options={
                'verbose_name': 'Message Agent IA',
                'verbose_name_plural': 'Messages Agent IA',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('artifact_type', models.CharField(choices=[('WG_REQUEST', "Demande d'attribution WG"), ('NORM_OVERLAP', 'Chevauchement de normes'), ('EXTERNAL_PROPOSAL', 'Proposition référentiel externe'), ('EMAIL_DRAFT', "Brouillon d'email"), ('CHART', 'Graphique')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('APPROVED', 'Approuvé'), ('SENT', 'Envoyé')], default='DRAFT', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='ia_agent.agentmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ia_agent.agentsession')),
            ],
            options={
                'verbose_name': 'Artefact Agent IA',
                'verbose_name_plural': 'Artefacts Agent IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['user', 'scope'], name='ia_agent_ag_user_id_6a0b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['session', 'created_at'], name='ia_agent_ag_session_9fed83_idx'),
        ),
        migrations.AddIndex(
            model_name='agentartifact',
            index=models.Index(fields=['session', 'artifact_type'], name='ia_agent_ag_session_4aeb01_idx'),
        ),
        migrations.AddIndex(
            model_name='agentartifact',
            index=models.Index(fields=['content_type', 'object_id'], name='ia_agent_ag_content_798a15_idx'),
        ),
    ]
