# Generated by Django 6.0.5 on 2026-06-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Claude (Anthropic)'), ('gemini', 'Gemini (Google)')], default='anthropic', max_length=20),
        ),
    ]
