# Generated by Django 6.0.5 on 2026-06-16 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_agent', '0002_agentsession_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentScopeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('scope', models.CharField(choices=[('expert', 'Expert'), ('ctc', 'Cellule Technique de Coordination'), ('pilotage', 'Comité de Pilotage')], max_length=20)),
                ('role_key', models.CharField(help_text='Clé unique du rôle (ex : pilotage_directoire, ctc_member, expert_active)', max_length=60)),
                ('label', models.CharField(help_text="Nom affiché dans l'admin", max_length=200)),
                ('system_prompt_extra', models.TextField(blank=True, help_text='Instructions supplémentaires ajoutées au prompt de base pour ce rôle.')),
                ('allowed_tools', models.JSONField(blank=True, help_text='Liste des outils autorisés pour ce rôle (null = tous les outils du scope). Ex : ["get_chart_data", "list_ctm_norms"]', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Agent IA — Rôle',
                'verbose_name_plural': 'Configurations Agent IA — Rôles',
                'ordering': ['scope', 'role_key'],
                'unique_together': {('scope', 'role_key')},
            },
        ),
    ]
