# Generated by Django 6.0.5 on 2026-06-16 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0011_platformfreeze'),
        ('ia_agent', '0004_agentscopeconfig_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPosteContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('organ', models.CharField(choices=[('pilotage', 'Comité de Pilotage Stratégique'), ('ctc', 'Cellule Technique de Coordination'), ('expert', 'Expert CTM/WG')], help_text='Organe auquel appartient ce poste', max_length=20)),
                ('sub_role', models.CharField(help_text='Clé du sous-rôle issue du moteur de privilèges (ex: president, rapporteur, coordonnateur_principal, foner)', max_length=60)),
                ('hierarchy_level', models.PositiveSmallIntegerField(choices=[(1, 'Niveau 1 — Président du COPIL'), (2, 'Niveau 2 — Bureau Directoire (VP / Secrétaire / Rapporteur)'), (3, 'Niveau 3 — Conseillers Institutionnels'), (4, 'Niveau 4 — Administrateurs Techniques et Financiers'), (5, 'Niveau 5 — Partenaires Sectoriels et Société Civile'), (6, 'Niveau 6 — Direction de la CTC'), (7, 'Niveau 7 — Pôles et Bureau Numérique CTC'), (8, 'Niveau 8 — Expert CTM / WG')], default=8, help_text='Niveau hiérarchique du poste (1 = plus élevé)')),
                ('position_label', models.CharField(help_text='Intitulé officiel complet du poste, affiché dans le prompt IA', max_length=500)),
                ('mission_summary', models.TextField(blank=True, help_text="Résumé de la mission et des responsabilités, pour contextualiser l'IA")),
                ('tools_hint', models.TextField(blank=True, help_text='Description des outils IA disponibles et des capacités spécifiques à ce poste')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('poste_ctc', models.OneToOneField(blank=True, help_text='Poste nominatif CTC lié (pour enrichissement relationnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_context', to='governance.postenominatifctc')),
                ('poste_pilotage', models.OneToOneField(blank=True, help_text='Poste nominatif Pilotage lié (pour enrichissement relationnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_context', to='governance.postenominatif')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contexte IA — Poste',
                'verbose_name_plural': 'Contextes IA — Postes (27 Pilotage + 19 CTC)',
                'ordering': ['organ', 'hierarchy_level', 'sub_role'],
                'unique_together': {('organ', 'sub_role')},
            },
        ),
    ]
