# Generated by Django 5.2.16 on 2026-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia_agent", "0006_agentpostecontext_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentartifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("WG_REQUEST", "Demande d'attribution WG"),
                    ("NORM_OVERLAP", "Chevauchement de normes"),
                    ("EXTERNAL_PROPOSAL", "Proposition référentiel externe"),
                    ("EMAIL_DRAFT", "Brouillon d'email"),
                    ("CHART", "Graphique"),
                    ("PUBLIC_INQUIRY_SYNTHESIS", "Synthèse enquête publique"),
                ],
                max_length=30,
            ),
        ),
    ]
