# Generated by Django 6.0.5 on 2026-05-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        ('norms', '0002_norme_jo_file_norme_jo_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegisticReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de légiste'), ('ASSIGNED', 'Attribué au légiste'), ('IN_REVIEW', 'En cours de toilettage'), ('REVIEW_COMPLETED', 'Toilettage terminé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Commentaires du légiste', null=True)),
                ('review_start_date', models.DateField(blank=True, null=True)),
                ('review_end_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('legist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_legist', to='experts.expert')),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legistic_review', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toilettage Légistique',
                'verbose_name_plural': 'Toilettages Légistiques',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
