# Generated by Django 6.0.5 on 2026-06-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expert_accepted_at_expert_accepted_by_and_more'),
        ('norms', '0004_normevote'),
        ('validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcologicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Attribué'), ('IN_REVIEW', 'En cours'), ('COMPLETED', 'Terminé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('impact_matrix', models.JSONField(blank=True, default=dict, help_text='Matrice JSON: {displacement, subsistence, heritage, environmental, sensitive_zones} → niveau')),
                ('comments', models.TextField(blank=True)),
                ('review_start_date', models.DateField(blank=True, null=True)),
                ('review_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_environmental_expert', to='experts.expert')),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecological_review', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen Sauvegardes Écologiques',
                'verbose_name_plural': 'Examens Sauvegardes Écologiques',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EconomicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Attribué'), ('IN_REVIEW', 'En cours'), ('COMPLETED', 'Terminé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('construction_cost_usd_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('annual_maintenance_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lifecycle_years', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lifecycle_cost_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Coût total cycle de vie calculé', max_digits=16, null=True)),
                ('comments', models.TextField(blank=True)),
                ('review_start_date', models.DateField(blank=True, null=True)),
                ('review_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_economist', to='experts.expert')),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economic_review', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation Économique',
                'verbose_name_plural': 'Évaluations Économiques',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustrialConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Attribué'), ('IN_REVIEW', 'En cours'), ('COMPLETED', 'Terminé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('fec_feedback', models.TextField(blank=True, help_text='Retours agrégés des entreprises BTP membres FEC')),
                ('companies_consulted', models.JSONField(blank=True, default=list, help_text='Liste des entreprises consultées')),
                ('market_feasible', models.BooleanField(blank=True, help_text='Norme applicable par le patronat privé', null=True)),
                ('review_start_date', models.DateField(blank=True, null=True)),
                ('review_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industrial_consultations', to='experts.expert')),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_consultation', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation Industrielle FEC',
                'verbose_name_plural': 'Consultations Industrielles FEC',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ISOReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Attribué'), ('IN_REVIEW', 'En cours'), ('COMPLETED', 'Terminé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('harmonization_notes', models.TextField(blank=True, help_text="Notes d'alignement ISO/SADC/RDC")),
                ('iso_references', models.CharField(blank=True, help_text='Références ISO applicables, ex: ISO 9001, ISO/TC 58', max_length=500)),
                ('review_start_date', models.DateField(blank=True, null=True)),
                ('review_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_iso_expert', to='experts.expert')),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iso_review', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen Veille ISO',
                'verbose_name_plural': 'Examens Veille ISO',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('planner_status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Attribué'), ('IN_REVIEW', 'En cours'), ('COMPLETED', 'Terminé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('scientist_status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Attribué'), ('IN_REVIEW', 'En cours'), ('COMPLETED', 'Terminé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('planner_notes', models.TextField(blank=True, help_text='Observations chronogramme et délais (J0→J+90)')),
                ('scientist_notes', models.TextField(blank=True, help_text="Validation état de l'art scientifique et mathématique")),
                ('review_start_date', models.DateField(blank=True, null=True)),
                ('review_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('norme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_review', to='norms.norme')),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_planner', to='experts.expert')),
                ('scientist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_scientist', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation Chronogramme & Scientifique',
                'verbose_name_plural': 'Validations Chronogramme & Scientifique',
                'ordering': ['-created_at'],
            },
        ),
    ]
