# Generated by Django 6.0.5 on 2026-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NORM_PUBLISHED', 'Norme publiée'), ('NORM_UPDATE', 'Mise à jour de norme'), ('NORM_AMENDED', 'Norme modifiée'), ('EXPERT_INVITE', 'Invitation expert'), ('EXPERT_ADDED_TO_WG', 'Ajouté à un groupe de travail'), ('REUNION_INVITE', 'Invitation à réunion'), ('MEETING_REMINDER', 'Rappel de réunion'), ('VOTE_OPEN', 'Vote ouvert'), ('VOTE_REMINDER', 'Rappel de vote'), ('AMENDMENT', 'Nouvel amendement'), ('PAYMENT_DUE', 'Cotisation due'), ('PAYMENT_RECEIVED', 'Paiement reçu'), ('PAYMENT_OVERDUE', 'Cotisation en retard'), ('MESSAGE', 'Nouveau message'), ('JETON', 'Jeton de présence'), ('SYSTEM', 'Notification système')], max_length=20),
        ),
    ]
