# Generated by Django 6.0.5 on 2026-06-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_emailconfirmationcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailconfirmationcode',
            new_name='mobileapp_e_user_id_34d23a_idx',
            old_name='mobileapp_e_user_id_4b7e3a_idx',
        ),
    ]
