# Generated by Django 6.0.5 on 2026-05-21 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('file', models.FileField(upload_to='experts_documents/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Image'), ('DOC', 'Document'), ('OTHER', 'Autre')], default='OTHER', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Ex: Justificatif, Rapport, Photo de réunion', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Expert',
                'verbose_name_plural': 'Documents Experts',
                'ordering': ['-created_at'],
            },
        ),
    ]
