# Generated by Django 6.0.5 on 2026-05-21 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('experts', '0001_initial'),
        ('meetings', '0001_initial'),
        ('norms', '0003_norme_lock_timeout_norme_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Taille en bytes'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Document visible publiquement'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='norme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='norms.norme'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meetings.reunion'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentfile',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='category',
            field=models.CharField(blank=True, help_text='Ex: Justificatif, Rapport, Annexe, Evidence', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_documents', to='experts.expert'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Image'), ('DOC', 'Document Word'), ('SHEET', 'Feuille de calcul'), ('VIDEO', 'Vidéo'), ('ARCHIVE', 'Archive (ZIP)'), ('OTHER', 'Autre')], default='OTHER', max_length=50),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='documents_d_uploade_2b6967_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['norme', '-created_at'], name='documents_d_norme_i_f3cc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['reunion', '-created_at'], name='documents_d_reunion_2fc745_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['is_public'], name='documents_d_is_publ_1953d3_idx'),
        ),
    ]
