# Generated by Django 6.0.5 on 2026-05-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('norms', '0003_norme_lock_timeout_norme_locked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAmendement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_by_name', models.CharField(help_text='Nom complet du proposant', max_length=255)),
                ('proposed_by_email', models.EmailField(help_text='Email du proposant (pour notification)', max_length=254)),
                ('proposed_by_organization', models.CharField(blank=True, help_text='Organisation/entreprise du proposant (optionnel)', max_length=255)),
                ('title', models.CharField(help_text="Titre court de l'amendement", max_length=255)),
                ('description', models.TextField(help_text="Description détaillée de l'amendement proposé")),
                ('justification', models.TextField(blank=True, help_text="Justification/rationale de l'amendement")),
                ('status', models.CharField(choices=[('PENDING', 'En attente de révision'), ('UNDER_REVIEW', "En cours d'examen"), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('ARCHIVED', 'Archivé')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes de révision par le CTC')),
                ('reviewed_by', models.CharField(blank=True, help_text='Nom du réviseur CTC', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_amendments', to='norms.norme')),
            ],
            options={
                'verbose_name': 'Amendement Public',
                'verbose_name_plural': 'Amendements Publics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['norme', 'status'], name='public_publ_norme_i_a61f03_idx'), models.Index(fields=['created_at'], name='public_publ_created_02dc6c_idx')],
            },
        ),
    ]
