# Generated by Django 5.2.16 on 2026-07-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicamendement",
            name="proposed_by_province",
            field=models.CharField(
                blank=True,
                help_text="Province de résidence du proposant (optionnel)",
                max_length=100,
            ),
        ),
    ]
