# Generated by Django 6.0.5 on 2026-05-19 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PARTIAL', 'Partiellement payée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard')], default='PENDING', max_length=20)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='experts.structure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_cotisation',
                'ordering': ['-annee', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='JetonPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PAID', 'Payé')], default='PENDING', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='experts.expert')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons_presence', to='meetings.reunion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_jetonpresence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('methode_paiement', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('AUTRE', 'Autre')], max_length=20)),
                ('numero_recu', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('numero_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('payment_date', models.DateField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='payments.cotisation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_paiement',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['structure', 'annee'], name='payments_co_structu_b5bdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['status', 'due_date'], name='payments_co_status_708d17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotisation',
            unique_together={('structure', 'annee')},
        ),
        migrations.AddIndex(
            model_name='jetonpresence',
            index=models.Index(fields=['expert', 'status'], name='payments_je_expert__ccfa35_idx'),
        ),
        migrations.AddIndex(
            model_name='jetonpresence',
            index=models.Index(fields=['reunion', 'status'], name='payments_je_reunion_c11e64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jetonpresence',
            unique_together={('expert', 'reunion')},
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['cotisation', 'status'], name='payments_pa_cotisat_056d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['payment_date', 'status'], name='payments_pa_payment_c7da74_idx'),
        ),
    ]
