# Generated by Django 6.0.5 on 2026-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        ('governance', '0002_add_hierarchy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='ctm_choices',
            field=models.ManyToManyField(blank=True, help_text="Sous-commissions sélectionnées par l'expert", related_name='member_experts', to='governance.ctm'),
        ),
    ]
