# Generated by Django 6.0.5 on 2026-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_expert_ctm_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taux journalier pour les jetons de présence (en USD)', max_digits=10),
        ),
        migrations.AddField(
            model_name='expert',
            name='monthly_research_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Indemnité mensuelle de recherche (en USD)', max_digits=10),
        ),
        migrations.AddField(
            model_name='expert',
            name='presence_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de présences cumulées aux sessions'),
        ),
    ]
