# Generated by Django 6.0.5 on 2026-06-01 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expert_daily_rate_expert_monthly_research_allowance_and_more'),
        ('governance', '0002_add_hierarchy_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='ctm_choices',
        ),
        migrations.AddField(
            model_name='expert',
            name='ctm',
            field=models.ForeignKey(blank=True, help_text="Sous-commission principale sélectionnée par l'expert", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_experts', to='governance.ctm'),
        ),
    ]
