# Generated by Django 6.0.5 on 2026-06-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expert_ctm_choices_expert_ctm'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="Numéro WhatsApp de l'expert", max_length=20),
        ),
    ]
