# Generated by Django 6.0.5 on 2026-06-06 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_expert_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts_accepted', to='experts.expert', verbose_name='Accepté par'),
        ),
        migrations.AddField(
            model_name='expert',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts_rejected', to='experts.expert', verbose_name='Rejeté par'),
        ),
        migrations.AddField(
            model_name='expert',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20),
        ),
    ]
