# Generated by Django 6.0.5 on 2026-05-19 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        ('norms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('section', models.CharField(help_text="Ex: '2.1.3'", max_length=100)),
                ('old_text', models.TextField()),
                ('proposed_text', models.TextField()),
                ('justification', models.TextField(help_text="Raison de l'amendement")),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposé'), ('UNDER_REVIEW', 'En révision'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('WITHDRAWN', 'Retiré')], default='PROPOSED', max_length=20)),
                ('proposal_date', models.DateTimeField(auto_now_add=True)),
                ('review_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='norms.norme')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendements_proposed', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendements', to='norms.normeversion')),
            ],
            options={
                'verbose_name': 'Amendement',
                'verbose_name_plural': 'Amendements',
                'ordering': ['-proposal_date'],
            },
        ),
        migrations.CreateModel(
            name='ResultatVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('votes_for', models.PositiveIntegerField(default=0)),
                ('votes_against', models.PositiveIntegerField(default=0)),
                ('votes_abstain', models.PositiveIntegerField(default=0)),
                ('quorum_reached', models.BooleanField(default=False)),
                ('approval_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text="Pourcentage d'approbation (Pour / Total)", max_digits=5)),
                ('vote_closed_at', models.DateTimeField(blank=True, null=True)),
                ('amendement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_vote', to='amendments.amendement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat Vote',
                'verbose_name_plural': 'Résultats Votes',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('vote', models.CharField(choices=[('FOR', 'Pour'), ('AGAINST', 'Contre'), ('ABSTAIN', 'Abstention')], max_length=10)),
                ('justification', models.TextField(blank=True, help_text='Justification optionnelle')),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('amendement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='amendments.amendement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendement_votes', to='experts.expert')),
            ],
            options={
                'verbose_name': 'Vote Amendement',
                'verbose_name_plural': 'Votes Amendements',
                'ordering': ['vote_date'],
            },
        ),
        migrations.AddIndex(
            model_name='amendement',
            index=models.Index(fields=['norme', 'status'], name='amendments__norme_i_bebb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='amendement',
            index=models.Index(fields=['status', 'proposal_date'], name='amendments__status_b425f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('amendement', 'voter')},
        ),
    ]
