# Generated by Django 6.0.5 on 2026-07-10 10:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ctm', models.CharField(max_length=200)),
                ('wg', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('input_json', models.JSONField(blank=True, null=True)),
                ('draft_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'gemini_drafts',
            },
        ),
    ]
