# Generated by Django 6.0.5 on 2026-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='draft',
            name='classification_reason',
            field=models.TextField(blank=True, help_text="Raison du choix du WG par l'IA"),
        ),
    ]
