# Generated by Django 6.0.5 on 2026-05-19 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=500)),
                ('reference_number', models.CharField(help_text='Ex: CNETP-001-2024', max_length=50, unique=True)),
                ('description', models.TextField()),
                ('iso_reference', models.CharField(blank=True, help_text='Ex: ISO 12345', max_length=50)),
                ('arso_reference', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('INTERNAL_REVIEW', 'En révision interne'), ('CTM_REVIEW', 'Soumis au CTM'), ('PUBLIC_INQUIRY', 'En enquête publique'), ('FINAL_REVIEW', 'En révision finale'), ('ADOPTED', 'Adopté'), ('HOMOLOGATED', 'Homologué'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('ctm_submission_date', models.DateField(blank=True, null=True)),
                ('public_inquiry_start', models.DateField(blank=True, null=True)),
                ('public_inquiry_end', models.DateField(blank=True, null=True)),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('homologation_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('current_version', models.FileField(blank=True, help_text='Dernière version du document', null=True, upload_to='norms/versions/')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par virgule', max_length=500)),
                ('is_public', models.BooleanField(default=False, help_text='Accessible au public?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('ctm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normes', to='governance.ctm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('wg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normes', to='governance.wg')),
            ],
            options={
                'verbose_name': 'Norme',
                'verbose_name_plural': 'Normes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='norms/versions/')),
                ('summary', models.TextField(blank=True, help_text='Résumé des changements')),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('version_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de Norme',
                'verbose_name_plural': 'Versions de Normes',
                'ordering': ['norme', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ChangementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('section', models.CharField(help_text="Ex: '2.1.3' ou 'Introduction'", max_length=100)),
                ('old_text', models.TextField(blank=True, help_text='Texte précédent')),
                ('new_text', models.TextField(help_text='Nouveau texte')),
                ('change_type', models.CharField(choices=[('ADD', 'Ajout'), ('REMOVE', 'Suppression'), ('MODIFY', 'Modification')], max_length=20)),
                ('change_reason', models.TextField(blank=True, help_text='Justification du changement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_from', to='norms.normeversion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='norms.normeversion')),
            ],
            options={
                'verbose_name': 'Changement Version',
                'verbose_name_plural': 'Changements Versions',
                'ordering': ['version', 'section'],
            },
        ),
        migrations.AddIndex(
            model_name='norme',
            index=models.Index(fields=['status', 'ctm'], name='norms_norme_status_c4f008_idx'),
        ),
        migrations.AddIndex(
            model_name='norme',
            index=models.Index(fields=['publication_date'], name='norms_norme_publica_c34ed4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='normeversion',
            unique_together={('norme', 'version_number')},
        ),
    ]
