# Generated by Django 6.0.5 on 2026-05-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='norme',
            name='jo_file',
            field=models.FileField(blank=True, help_text='Scan de la publication au JO', null=True, upload_to='norms/jo/'),
        ),
        migrations.AddField(
            model_name='norme',
            name='jo_reference',
            field=models.CharField(blank=True, help_text='Référence au Journal Officiel', max_length=100),
        ),
        migrations.AddField(
            model_name='norme',
            name='legistic_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='norme',
            name='pilotage_validation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='norme',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('INTERNAL_REVIEW', 'En révision interne'), ('CTM_REVIEW', 'Soumis au CTM'), ('LEGISTIC_REVIEW', 'Toilettage légistique'), ('PUBLIC_INQUIRY', 'En enquête publique'), ('PILOTAGE_REVIEW', 'Validation Comité Pilotage'), ('FINAL_REVIEW', 'En révision finale'), ('ADOPTED', 'Adopté'), ('HOMOLOGATED', 'Homologué'), ('PUBLISHED', 'Publié au JO'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20),
        ),
    ]
