# Generated by Django 6.0.5 on 2026-05-21 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0002_norme_jo_file_norme_jo_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='norme',
            name='lock_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='norme',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_norms', to=settings.AUTH_USER_MODEL),
        ),
    ]
