# Generated by Django 6.0.5 on 2026-06-04 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_expert_whatsapp_number'),
        ('norms', '0003_norme_lock_timeout_norme_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('vote', models.CharField(choices=[('FOR', 'Pour'), ('AGAINST', 'Contre'), ('ABSTAIN', 'Abstention')], max_length=10)),
                ('justification', models.TextField(blank=True)),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('norme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='norms.norme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norme_votes', to='experts.expert')),
            ],
            options={
                'verbose_name': 'Vote Norme',
                'verbose_name_plural': 'Votes Normes',
                'ordering': ['-vote_date'],
                'indexes': [models.Index(fields=['norme', 'vote'], name='norms_norme_vote_idx')],
                'unique_together': {('norme', 'voter')},
            },
        ),
    ]
