# Generated by Django 6.0.5 on 2026-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0004_normevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='norme',
            name='norm_type',
            field=models.CharField(choices=[('NCD', 'Norme Nationale Congolaise'), ('CA', 'Code Applicatif'), ('DIR', 'Directive Technique'), ('REC', 'Recommandation Technique')], default='NCD', max_length=3),
        ),
        migrations.AddField(
            model_name='norme',
            name='target_count',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de normes individuelles couvertes par cette ligne de planification'),
        ),
    ]
