# Generated by Django 6.0.5 on 2026-07-05 00:00

from django.db import migrations, models


def infer_standard_family(apps, schema_editor):
    Norme = apps.get_model('norms', 'Norme')
    for norme in Norme.objects.all():
        family = 'NCD'
        if norme.iso_reference:
            family = 'ISO'
        elif norme.arso_reference:
            family = 'ARSO'
        elif norme.reference_number.startswith('CNETP-CTM3-ISO-'):
            family = 'ISO'
        norme.standard_family = family
        norme.save(update_fields=['standard_family'])


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0006_normecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='norme',
            name='standard_family',
            field=models.CharField(choices=[('NCD', 'Norme Nationale Congolaise'), ('ISO', 'Référentiel ISO'), ('ARSO', 'Référentiel ARSO'), ('OTHER', 'Autre référentiel')], default='NCD', max_length=10),
        ),
        migrations.RunPython(infer_standard_family, migrations.RunPython.noop),
    ]
