# Generated by Django 6.0.5 on 2026-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0007_norme_standard_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='norme',
            name='category',
            field=models.CharField(blank=True, help_text="Catégorie d'activité (ex: Qualité, Sécurité, Éthique)", max_length=100),
        ),
    ]
