# Generated by Django 6.0.5 on 2026-07-07 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0008_norme_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormeContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('kind', models.CharField(choices=[('SECTION', 'Section'), ('ARTICLE', 'Article'), ('ANNEXE', 'Annexe'), ('PARAGRAPH', 'Paragraphe')], max_length=20)),
                ('code', models.CharField(blank=True, help_text='Ex: 1, 1.1, A', max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='norms.normecontentblock')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='norms.normeversion')),
            ],
            options={
                'verbose_name': 'Bloc de contenu de norme',
                'verbose_name_plural': 'Blocs de contenu de norme',
                'ordering': ['version', 'position', 'id'],
                'unique_together': {('version', 'position')},
            },
        ),
    ]
