# Generated by Django 6.0.5 on 2026-07-08 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0009_normecontentblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormeDocumentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('source_path', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('guide', 'Guide'), ('liste_normes', 'Liste des normes'), ('norme', 'Norme'), ('inconnu', 'Inconnu')], max_length=50)),
                ('paragraph_count', models.PositiveIntegerField(default=0)),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document normatif importé',
                'verbose_name_plural': 'Documents normatifs importés',
                'ordering': ['-imported_at', 'filename'],
            },
        ),
    ]
