# Generated by Django 6.0.5 on 2026-07-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0010_normedocumentimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='normedocumentimport',
            name='norme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_imports', to='norms.norme'),
        ),
    ]
