# Generated by Django 6.0.5 on 2026-05-19 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type', models.CharField(choices=[('CTM', 'Comité Technique Miroir'), ('WG', 'Groupe de Travail'), ('PILOTAGE', 'Comité de Pilotage'), ('ASSEMBLEE', 'Assemblée Plénière'), ('CTC', 'Cellule Technique de Coordination')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_reunion_virtuelle', models.URLField(blank=True, null=True)),
                ('ordre_jour', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Complétée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_organisees', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings_reunion',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessusVerbaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('nombre_presents', models.IntegerField(default=0)),
                ('nombre_absents', models.IntegerField(default=0)),
                ('quorum_atteint', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('signature_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_signed', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='meetings.reunion')),
            ],
            options={
                'db_table': 'meetings_processusvverbaux',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excusé')], default='PRESENT', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='experts.expert')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_marked', to='experts.expert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='meetings.reunion')),
            ],
            options={
                'db_table': 'meetings_presence',
            },
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['type', 'date'], name='meetings_re_type_7a0c56_idx'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['status', 'date'], name='meetings_re_status_0453e6_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['reunion', 'status'], name='meetings_pr_reunion_bb34fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('reunion', 'expert')},
        ),
    ]
