# Generated by Django 6.0.5 on 2026-05-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_message'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='meetings_me_reunion_45ec28_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='meetings_me_sender__4b24fb_idx',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
