# Generated by Codex on 2026-06-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_alter_pilotagemembreship_role_tache'),
        ('meetings', '0003_remove_message_meetings_me_reunion_45ec28_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='ctm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions', to='governance.ctm'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='document_reglementaire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reunion',
            name='wg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions', to='governance.wg'),
        ),
        migrations.CreateModel(
            name='ReunionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('choix', models.CharField(choices=[('POUR', 'Pour'), ('CONTRE', 'Contre'), ('ABSTENTION', 'Abstention')], max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunion_votes', to='experts.expert')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meetings.reunion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings_reunionvote',
                'indexes': [models.Index(fields=['reunion', 'choix'], name='meetings_re_reunion_581dc1_idx')],
                'unique_together': {('reunion', 'expert')},
            },
        ),
    ]
